/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rahul.converter;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IllegalAccessException {
//        IntegerCoverter ic= new IntegerCoverter();
//        System.out.println(ic.getRoman(140).toString());
        RomanToInt rm=new RomanToInt();
        System.out.println(rm.romanToInt("I"));
    }
}
